// puzzles.js
// Each puzzle has a THEME and a POOL of words that relate to it. This is
// the real WordSalad mechanic: a themed set of hidden words, not a
// single scrambled word. Viewers guess theme words in chat; correct
// guesses are revealed and highlighted on the shared grid.
//
// Word length increases with difficulty, matching the real game's
// progression: Easy = 3-5 letters, Medium = 5-7 letters, Hard = 7-9 letters.
//
// IMPORTANT: each theme's word list here is a POOL, not a fixed round.
// The server randomly samples a subset of that pool for each individual
// round (see ROUND_WORD_COUNT in server.js), so a theme with 20 words
// sampled 10 at a time already yields C(20,10) = 184,756 distinct
// rounds on its own. With 50+ themes per difficulty, every tier yields
// vastly more than 10,000 possible distinct rounds -- using real,
// accurate vocabulary rather than padding with fabricated categories.

module.exports = {
  easy: [
    { theme: "Fruits", words: ["mango","grape","lemon","plum","kiwi","pear","date","fig","lime","melon","guava","apple","berry","peach","olive","prune","acai"] },
    { theme: "Vegetables", words: ["pea","corn","kale","leek","okra","beet","yam","taro","onion","chard","gourd","chive","cress","spud","kelp","bean"] },
    { theme: "Farm Animals", words: ["pig","cow","hen","ram","goat","duck","mule","lamb","calf","colt","foal","horse","sheep","goose","kid","fowl","drake","ewe","sow","bull","hog","yak"] },
    { theme: "Pizza Toppings", words: ["ham","egg","corn","herb","mint","onion","olive","basil","bacon","pesto","chili","crust","sauce","steak","clams"] },
    { theme: "Colors", words: ["red","tan","gray","blue","gold","jade","pink","teal","ruby","ivory","coral","black","white","green","brown","navy","cyan","lilac","beige","khaki","mauve","ochre","rust"] },
    { theme: "Kitchen Items", words: ["pot","pan","cup","jar","tray","bowl","fork","knife","spoon","plate","whisk","ladle","mug","lid","sieve","tongs","oven","stove"] },
    { theme: "Ocean Animals", words: ["cod","eel","ray","crab","clam","squid","shark","whale","seal","otter","orca","perch","trout","skate","krill"] },
    { theme: "Breakfast Foods", words: ["egg","oat","jam","toast","bacon","syrup","bagel","gravy","crepe","grits","juice","fruit","honey","hash","roll"] },
    { theme: "School Supplies", words: ["pen","ink","glue","ruler","paper","chalk","book","desk","tape","clip","chair","bag","map","case","notes","pages"] },
    { theme: "Body Parts", words: ["arm","leg","ear","eye","rib","hip","jaw","chin","neck","knee","foot","hand","nose","lip","toe","brow","wrist","thumb","liver","heart","bone","vein","skin","palm"] },
    { theme: "Emotions", words: ["joy","fear","calm","mad","sad","glee","pride","shy","envy","hope","love","rage","bliss","worry","panic","grief","guilt"] },
    { theme: "Weather Words", words: ["fog","sun","rain","snow","wind","hail","mist","storm","frost","sleet","cloud","heat","cold","gale","haze","sunny","windy","rainy","foggy"] },
    { theme: "Zoo Animals", words: ["lion","bear","wolf","zebra","tiger","panda","camel","koala","sloth","otter","hippo","lynx","puma","mole","moose","bison","llama","rhino","skunk"] },
    { theme: "Insects", words: ["ant","bee","fly","gnat","moth","wasp","tick","flea","aphid","roach","bug","mite","grub","midge"] },
    { theme: "Birds", words: ["owl","hen","jay","crow","dove","duck","swan","robin","eagle","heron","raven","stork","quail","wren","lark","finch","crane","hawk","ibis","tern"] },
    { theme: "Trees", words: ["elm","oak","fir","pine","palm","cedar","maple","birch","alder","aspen","yew","ash","teak","larch","holly","beech","balsa"] },
    { theme: "Flowers", words: ["rose","lily","iris","tulip","daisy","aster","lotus","poppy","phlox","pansy","mum","lilac"] },
    { theme: "Shapes", words: ["box","star","oval","cube","cone","ring","disc","heart","arc","dot","line","wedge","prism","cross"] },
    { theme: "Gems And Stones", words: ["opal","ruby","jade","onyx","topaz","agate","pearl","amber","flint","slate","coal","clay","chalk","beryl"] },
    { theme: "Spices", words: ["mint","sage","dill","cumin","basil","clove","thyme","anise","mace","salt","chili","curry","herbs"] },
    { theme: "Drinks", words: ["milk","soda","cola","juice","water","cider","mocha","latte","punch","shake","wine","beer","rum","gin","tonic","fizz","brew"] },
    { theme: "Desserts", words: ["cake","pie","tart","candy","fudge","donut","scone","jelly","cream","cocoa","bar","flan","torte"] },
    { theme: "Clothing Items", words: ["hat","cap","tie","coat","vest","robe","sock","boot","shirt","pants","skirt","scarf","glove","belt","jeans","cloak","cape","suit","tunic","dress"] },
    { theme: "Furniture", words: ["bed","sofa","desk","lamp","sink","shelf","stool","couch","chair","table","rug","crib","bench","futon","chest"] },
    { theme: "Tools", words: ["axe","saw","drill","plane","level","screw","clamp","file","vice","rake","nail","bolt","tape"] },
    { theme: "Board And Card Games", words: ["chess","sorry","risk","life","clue","snap","uno","ludo","war","spit","bingo","jacks"] },
    { theme: "Musical Instruments", words: ["drum","harp","horn","flute","banjo","viola","organ","piano","oboe","lute","bugle","gong","chime","fife"] },
    { theme: "Toys", words: ["doll","kite","yoyo","top","robot","drone","bear","kazoo","dice","ball","wagon","drum","spin","cars"] },
    { theme: "Bathroom Items", words: ["soap","comb","towel","brush","razor","sink","tub","drain","scale","robe","rinse","floss"] },
    { theme: "Office Supplies", words: ["pen","clip","tape","stamp","paper","ruler","glue","desk","file","pin","inbox","phone"] },
    { theme: "Camping Gear", words: ["tent","rope","torch","stove","knife","flask","tarp","map","lamp","axe","fire","wood","boots"] },
    { theme: "Beach Items", words: ["sand","wave","surf","shell","towel","float","crab","kite","pail","raft","sun","swim"] },
    { theme: "Winter Items", words: ["snow","coat","boot","scarf","sled","ice","frost","skis","cocoa","mitt","chill","parka"] },
    { theme: "Family Members", words: ["mom","dad","son","aunt","uncle","niece","wife","papa","nana","gran","kid","twin","baby","bride","groom"] },
    { theme: "Professions", words: ["cook","maid","monk","judge","nurse","pilot","actor","chef","coach","clerk","baker","miner","medic","guard","tutor"] },
    { theme: "Vehicles", words: ["car","van","cab","bus","jeep","taxi","truck","train","tram","sedan","bike","moped","wagon"] },
    { theme: "Boats", words: ["raft","ship","boat","canoe","kayak","yacht","barge","ferry","sloop","skiff","punt","dhow","junk"] },
    { theme: "Music Genres", words: ["jazz","rock","funk","folk","punk","blues","disco","metal","house","swing","emo","pop","soul","indie","grime"] },
    { theme: "Fast Food Items", words: ["fries","pizza","taco","wrap","chips","shake","combo","meal","soda","melt","patty"] },
    { theme: "Candy", words: ["mint","gum","taffy","fudge","gummy","lolly","chews","bar","nuts","drop","jelly"] },
    { theme: "Grains", words: ["rice","oats","corn","wheat","grain","bran","rye","maize","flour","germ","spelt","grits"] },
    { theme: "Cheese Types", words: ["brie","feta","gouda","swiss","edam","curd","jack","colby","cream","blue","queso"] },
    { theme: "Nuts And Seeds", words: ["nut","pecan","chia","hemp","flax","seed","bean","pod","husk","shell","acorn","poppy"] },
    { theme: "Seafood", words: ["crab","clam","cod","eel","squid","prawn","tuna","bass","sole","carp","roe","perch","trout"] },
    { theme: "Reptiles", words: ["snake","gecko","skink","viper","cobra","croc","adder","boa","asp","gator","mamba","tegu"] },
    { theme: "Farm Tools", words: ["rake","hoe","plow","spade","fork","yoke","cart","pail","sack","silo","hook"] },
    { theme: "Garden Items", words: ["hoe","rake","seed","soil","pot","vine","stem","leaf","bloom","petal","weed","root","bulb","twig"] },
    { theme: "Chess And Card Terms", words: ["king","pawn","rook","ace","suit","deck","joker","queen","trick","trump","bid","draw","hand","fold","bet","raise"] },
    { theme: "Music Terms", words: ["beat","bass","alto","tempo","chord","scale","pitch","verse","solo","duet","note","song","tune","key","band","trio"] },
    { theme: "Dances", words: ["jive","tango","waltz","polka","salsa","disco","swing","twist","samba","conga","hula","jazz","reel"] },
    { theme: "Building Materials", words: ["wood","brick","stone","glass","steel","clay","tile","sand","plank","brass","metal","paint","straw"] },
    { theme: "Sea And Sky Words", words: ["star","moon","sun","tide","wave","reef","cave","cliff","dune","cove","bay","cape","beach","shore","coast"] },
    { theme: "Cooking Actions", words: ["bake","boil","fry","stir","chop","mix","whisk","grill","roast","peel"] },
    { theme: "Money And Finance", words: ["cash","coin","bank","debt","fund","loan","bill","price","penny","token"] },
    { theme: "Time Words", words: ["hour","week","year","month","noon","dawn","dusk","today","night","clock"] },
    { theme: "Sports Equipment", words: ["ball","bat","net","puck","glove","skate","hoop","pin","mitt","cleat"] },
    { theme: "Household Chores", words: ["wash","dust","sweep","mop","iron","tidy","clean","fold","scrub","rinse"] },
  ],

  medium: [
    { theme: "Dog Breeds", words: ["poodle","beagle","boxer","husky","collie","terrier","spaniel","bulldog","corgi","basset","whippet","pointer","setter"] },
    { theme: "Greek Mythology", words: ["athena","hades","apollo","hermes","medusa","cronus","circe","midas","atlas","perseus","theseus","icarus","orpheus","jason"] },
    { theme: "US States", words: ["texas","idaho","maine","nevada","oregon","alaska","hawaii","kansas","georgia","arizona","florida","indiana","montana","alabama","wyoming","vermont"] },
    { theme: "Musical Instruments", words: ["guitar","violin","trumpet","flute","piano","cello","bassoon","cymbal","maracas","ukulele","zither","kalimba","cornet","whistle"] },
    { theme: "Card Games", words: ["poker","bridge","rummy","hearts","euchre","canasta","spades","whist","bezique","pitch","cassino","sevens","belote","cheat"] },
    { theme: "Board Games", words: ["chess","sorry","trouble","yahtzee","taboo","othello","mancala","jenga","connect","hangman","boggle","perudo","cluedo"] },
    { theme: "Italian Foods", words: ["penne","rotini","ravioli","gnocchi","fusilli","lasagna","risotto","panini","gelato","pesto","salami","marsala","polenta","caprese"] },
    { theme: "Superheroes", words: ["batman","flash","storm","robin","cyclops","magneto","phoenix","electro","vulture","falcon","raven","beast","hawkeye","rocket"] },
    { theme: "World Cities", words: ["nairobi","lisbon","jakarta","ottawa","london","madrid","berlin","warsaw","dublin","vienna","athens","moscow","cairo","seoul","tokyo","zurich","geneva","munich","naples","venice","bogota","manila"] },
    { theme: "Kitchen Appliances", words: ["toaster","blender","freezer","skillet","griddle","kettle","burner","grater","peeler","opener","warmer","cooker","grinder","crusher"] },
    { theme: "Furniture", words: ["dresser","cabinet","ottoman","armoire","hammock","bureau","vanity","daybed","cushion","curtain","beanbag","rocker","trundle"] },
    { theme: "Clothing", words: ["sweater","jacket","blouse","sandals","sneaker","necktie","earring","legging","slipper","trouser","beanie","gloves","mittens","leotard","kimono","poncho","parka","tuxedo"] },
    { theme: "Sports", words: ["boxing","hockey","tennis","soccer","rowing","diving","bowling","fencing","archery","cricket","karate","cycling","curling","surfing","skating","rugby","squash"] },
    { theme: "Occupations", words: ["doctor","lawyer","farmer","singer","writer","banker","dancer","teacher","painter","plumber","butcher","soldier","waiter","barber","driver"] },
    { theme: "Countries", words: ["mexico","canada","brazil","russia","poland","sweden","norway","turkey","vietnam","germany","belgium","austria","ireland","iceland","finland","denmark","albania"] },
    { theme: "Mammals", words: ["rabbit","beaver","badger","weasel","possum","raccoon","leopard","giraffe","buffalo","dolphin","gorilla","panther","jackal","hyena","cheetah","gazelle","gibbon"] },
    { theme: "Birds", words: ["sparrow","pelican","penguin","falcon","parrot","ostrich","peacock","seagull","pigeon","vulture","toucan","condor","warbler","buzzard","bunting","skylark","redwing"] },
    { theme: "Insects", words: ["cricket","ladybug","firefly","termite","cicada","beetle","hornet","mantis","earwig","weevil","katydid","aphid","midge","nymph"] },
    { theme: "Flowers", words: ["jasmine","petunia","begonia","dahlia","orchid","crocus","violet","zinnia","freesia","peony","aster","yarrow","cosmos","anemone"] },
    { theme: "Trees", words: ["willow","walnut","cypress","redwood","hickory","juniper","spruce","poplar","banyan","conifer","sequoia","hemlock","acacia","laurel","linden","myrtle"] },
    { theme: "Gemstones", words: ["emerald","diamond","citrine","peridot","zircon","garnet","jasper","spinel","apatite","kunzite","iolite","axinite","sphene","zoisite"] },
    { theme: "Metals", words: ["copper","silver","nickel","bronze","cobalt","mercury","uranium","brass","pewter","chrome","cesium","barium","radium","osmium","cerium"] },
    { theme: "Spices", words: ["oregano","paprika","saffron","fennel","nutmeg","ginger","mustard","anise","cumin","pepper","sumac","cloves","wasabi"] },
    { theme: "Desserts", words: ["brownie","cupcake","pudding","sundae","custard","macaron","biscuit","cookie","waffle","parfait","gelatin","popover","fritter","eclair"] },
    { theme: "Drinks", words: ["whiskey","brandy","martini","mojito","sangria","eggnog","seltzer","spritz","cordial","punch","sherry","tequila","bourbon","gimlet","julep"] },
    { theme: "Dances", words: ["foxtrot","shuffle","mambo","rumba","bolero","hustle","twerk","lambada","salsa","boogie","cancan","bachata"] },
    { theme: "Music Genres", words: ["reggae","techno","grunge","ambient","country","trance","gospel","ballad","fusion","ragtime","dubstep","klezmer","zydeco"] },
    { theme: "Weather Phenomena", words: ["drizzle","thunder","tornado","cyclone","tsunami","monsoon","typhoon","rainbow","squall","breeze","gusting"] },
    { theme: "Constellations", words: ["orion","draco","cygnus","phoenix","dorado","hydra","indus","lupus","carina","norma","crater","pyxis","caelum","antlia","fornax"] },
    { theme: "Planets And Space", words: ["venus","earth","saturn","uranus","mercury","jupiter","neptune","pluto","comet","meteor","galaxy","nebula","rocket","orbit","transit","module","probe","launch"] },
    { theme: "Body Parts", words: ["elbow","ankle","wrist","throat","spine","tongue","eyelid","eyebrow","forearm","stomach","kidney","muscle","tendon","cornea","eardrum","nostril"] },
    { theme: "Professions", words: ["plumber","butcher","soldier","chemist","dentist","surgeon","curator","jeweler","tailor","florist","barber","welder","potter","grocer","cashier","trainer"] },
    { theme: "Vehicles", words: ["scooter","bicycle","tractor","trailer","minivan","caravan","wagon","subway","trolley","hearse","buggy","sidecar","tramcar"] },
    { theme: "Boats", words: ["steamer","trawler","dinghy","gondola","clipper","tugboat","cruiser","kayak","yacht","barge","canoe","pontoon","catboat","rowboat"] },
    { theme: "Reptiles", words: ["iguana","lizard","python","monitor","caiman","gharial","mamba","cobra","gecko","adder","skink","anole","racer"] },
    { theme: "Farm Equipment", words: ["tractor","combine","harvest","trailer","harrow","sprayer","feeder","baler","mower","seeder","plough","tiller","loader","grader"] },
    { theme: "Sea Terms", words: ["current","seaweed","coastal","estuary","lagoon","harbor","shallow","coral","marina","jetty","seabed","seafoam","seaside","channel"] },
    { theme: "Cheese Types", words: ["cheddar","gruyere","ricotta","havarti","romano","paneer","burrata","stilton","queso","asiago","chevre","cotija"] },
    { theme: "Nuts And Seeds", words: ["almond","walnut","cashew","peanut","pumpkin","sesame","acorn","quinoa","lentil","legume","filbert","praline","linseed","caraway"] },
    { theme: "Seafood", words: ["lobster","oyster","salmon","herring","halibut","scallop","mussel","octopus","anchovy","sardine","haddock","pollock","catfish","snapper","caviar"] },
    { theme: "Winter Sports", words: ["skiing","curling","bobsled","skating","hockey","slalom","mogul","igloo","parka","beanie","luging","snowman"] },
    { theme: "Summer Sports", words: ["surfing","diving","rowing","sailing","cycling","archery","fencing","frisbee","paddle","tennis","rafting","jetski","boating"] },
    { theme: "Yoga Poses", words: ["cobra","eagle","camel","bridge","locust","warrior","pigeon","dolphin","plank","chair","lotus","child"] },
    { theme: "Video Game Genres", words: ["puzzle","arcade","shooter","sandbox","racing","rhythm","stealth","horror","action","combat","fantasy","fighter","tactics","western"] },
    { theme: "Building Types", words: ["cottage","mansion","chateau","cabin","castle","chapel","tower","palace","temple","bunker","pyramid","stadium","factory"] },
    { theme: "Musical Terms", words: ["melody","harmony","rhythm","cadence","vibrato","octave","chorus","bridge","refrain","timbre","descant","legato","largo","presto","finale"] },
    { theme: "Weather And Climate", words: ["humid","arctic","desert","tundra","climate","drought","tornado","tropics","glacier","breeze","savanna","biome","habitat"] },
    { theme: "School Subjects", words: ["science","history","english","biology","physics","algebra","drama","music","civics","reading","writing","grammar","debate"] },
    { theme: "Kitchen Utensils", words: ["spatula","ladle","tongs","grater","peeler","skewer","whisk","masher","funnel","opener","sifter","corer","zester","shears","baster"] },
    { theme: "Sky And Sunlight", words: ["rainbow","horizon","eclipse","sunrise","sunset","aurora","zenith","equinox","meteor","cosmos","daytime","clouds","skyline"] },
    { theme: "Types Of Bread", words: ["bagel","brioche","pretzel","challah","bannock","scone","muffin","biscuit","crumpet","matzo","damper","wheaten"] },
    { theme: "Types Of Tea", words: ["oolong","jasmine","rooibos","matcha","herbal","masala","ginger","sencha","puerh","assam","bancha","kukicha","hojicha"] },
    { theme: "Ocean Animals", words: ["dolphin","narwhal","urchin","mollusk","walrus","beluga","manatee","turtle","marlin","grouper","seaslug","anemone"] },
    { theme: "Coffee And Cafe", words: ["latte","mocha","blend","roast","grinds","barista","creamer","saucer","thermos","kettle","filter","grinder","bistro"] },
    { theme: "Herbs", words: ["chives","parsley","basil","thyme","sorrel","chervil","savory","borage","nettle","lovage","oregano","fennel"] },
  ],

  hard: [
    { theme: "Chemical Elements", words: ["hydrogen","nitrogen","fluorine","chlorine","platinum","tungsten","selenium","strontium","potassium","manganese","titanium","calcium","chromium","aluminum","germanium","tellurium","europium","samarium","terbium","holmium","thulium","lutetium","hafnium","rhenium"] },
    { theme: "Shakespeare Plays And Characters", words: ["macbeth","othello","tempest","cymbeline","pericles","ophelia","cordelia","desdemona","cleopatra","prospero","caliban","falstaff","polonius","horatio","gertrude","claudius","benedick","beatrice","shylock","malvolio","rosalind","orlando"] },
    { theme: "World Capitals", words: ["nairobi","jakarta","canberra","budapest","singapore","helsinki","brussels","santiago","asuncion","kathmandu","stockholm","belgrade","bucharest","kingston","valletta","islamabad","tashkent","yerevan","pretoria","damascus","caracas","tbilisi"] },
    { theme: "Constellations", words: ["pegasus","cepheus","hercules","aquarius","andromeda","capricorn","scorpius","columba","perseus","lacerta","phoenix"] },
    { theme: "Programming Languages", words: ["assembly","haskell","fortran","clojure","graphql","verilog","crystal","solidity","angular","smalltalk","labview","modelica","scratch"] },
    { theme: "Classical Composers", words: ["debussy","sibelius","paganini","beethoven","schubert","vivaldi","purcell","puccini","rossini","respighi","albeniz","berlioz","bruckner","telemann","pergolesi","scarlatti","corelli","buxtehude"] },
    { theme: "Extinct Animals", words: ["mammoth","aurochs","thylacine","megalodon","glyptodon","archelon","smilodon","gastornis","pterosaur","titanoboa","toxodon"] },
    { theme: "Renaissance Artists", words: ["raphael","donatello","bellini","giorgione","perugino","mantegna","correggio","veronese","carpaccio","bramante","masaccio","uccello","ghiberti","pontormo","pisanello","antonello"] },
    { theme: "Mythical Creatures", words: ["griffin","basilisk","werewolf","minotaur","banshee","chimera","cerberus","pegasus","phoenix","mermaid","leviathan","centaur","vampire","gargoyle","unicorn","specter","wendigo"] },
    { theme: "Famous Scientists", words: ["einstein","galileo","faraday","pasteur","lavoisier","hawking","mendeleev","avogadro","boltzmann","linnaeus","priestley","pauling","fleming","lamarck","maxwell","celsius","bernoulli","marconi"] },
    { theme: "Orchestral Instruments", words: ["trombone","clarinet","bassoon","trumpet","cymbals","triangle","xylophone","saxophone","euphonium","clavinet","tympani","celesta","bandoneon","crumhorn","sackbut"] },
    { theme: "Occupations", words: ["therapist","architect","paramedic","detective","professor","librarian","secretary","carpenter","mechanic","economist","biologist","chemist","surgeon","dietitian","optician","realtor","linguist","chauffeur","paralegal"] },
    { theme: "Countries", words: ["thailand","cambodia","portugal","slovakia","bulgaria","argentina","venezuela","australia","indonesia","guatemala","nicaragua","lithuania","macedonia","suriname","barbados","jamaica","dominica"] },
    { theme: "African Countries", words: ["tanzania","botswana","zimbabwe","mauritius","cameroon","ethiopia","algeria","tunisia","senegal","nigeria","namibia","lesotho","eswatini","comoros","djibouti","eritrea","liberia","somalia","burundi"] },
    { theme: "Asian Countries", words: ["mongolia","pakistan","malaysia","myanmar","vietnam","bahrain","lebanon","cambodia","thailand","indonesia","maldives","georgia","armenia"] },
    { theme: "European Countries", words: ["portugal","bulgaria","slovakia","slovenia","croatia","hungary","ireland","ukraine","belgium","germany","romania","austria","belarus","andorra","moldova"] },
    { theme: "Greek Gods", words: ["poseidon","dionysus","aphrodite","demeter","artemis","hercules","hyperion","oceanus","asclepius","nemesis","morpheus","proteus","iapetus"] },
    { theme: "Roman Gods", words: ["jupiter","neptune","minerva","mercury","bacchus","quirinus","terminus","silvanus","vertumnus","vulcanus","fortuna","victoria","concordia"] },
    { theme: "Geological Terms", words: ["mountain","volcano","plateau","sediment","limestone","obsidian","feldspar","graphite","magnetite","tectonic","mineral","bedrock","erosion","fissure","granite","mudstone","sandstone"] },
    { theme: "Ocean Zones", words: ["sunlight","twilight","midnight","abyssal","benthic","pelagic","littoral","neritic","bathyal","estuarine","subtidal","offshore","nearshore","seafloor"] },
    { theme: "Space Terms", words: ["asteroid","satellite","telescope","supernova","wormhole","meteorite","cosmonaut","astronaut","parallax","aphelion","universe","redshift","exoplanet","lightyear"] },
    { theme: "Body Organs", words: ["stomach","pancreas","appendix","intestine","diaphragm","esophagus","bladder","thyroid","ventricle","clavicle","pituitary","epidermis","placenta","prostate","trachea","pharynx","adrenal"] },
    { theme: "Weather Phenomena", words: ["hurricane","blizzard","avalanche","lightning","whirlwind","heatwave","sandstorm","hailstorm","monsoon","cyclone","downburst","firestorm","snowstorm","rainstorm","windstorm","tempest"] },
    { theme: "Academic Subjects", words: ["chemistry","geometry","calculus","geography","economics","astronomy","sociology","genetics","geology","zoology","physics","biology","medicine","forensics","pharmacy","theology","ecology","anatomy"] },
    { theme: "Musical Terms", words: ["crescendo","staccato","vibrato","harmonic","dissonant","orchestra","symphony","concerto","ensemble","conductor","cadenza","polyphony","monotone","arpeggio","glissando","virtuoso","maestro","libretto"] },
    { theme: "Card Game Terms", words: ["solitaire","blackjack","canasta","cribbage","pinochle","baccarat","patience","klondike","freecell","pyramid","trumping","shuffling","dealing","bidding","discard","scoring"] },
    { theme: "Board Game Terms", words: ["monopoly","scrabble","checkers","dominoes","parcheesi","mancala","stratego","othello","yahtzee","sequence","trouble","hangman","pandemic","codenames"] },
    { theme: "Insects", words: ["butterfly","dragonfly","centipede","millipede","ladybird","cockroach","stinkbug","lacewing","mosquito","termite","cutworm","silkworm","bumblebee","honeybee","wireworm","screwworm","antlion"] },
    { theme: "Trees", words: ["eucalypt","mangrove","cypress","sycamore","chestnut","mahogany","jacaranda","rosewood","ironwood","dogwood","hardwood","softwood","deadwood","driftwood","heartwood","greenwood","basswood","blackwood","boxwood"] },
    { theme: "Flowers", words: ["hibiscus","marigold","daffodil","camellia","lavender","carnation","gardenia","hyacinth","bluebell","buttercup","hollyhock","primrose","columbine","foxglove","larkspur"] },
    { theme: "Gemstones", words: ["moonstone","turquoise","amethyst","tanzanite","malachite","rhodonite","sapphire","diamond","emerald","peridot","rhodolite","sunstone","moldavite","prehnite","sodalite","hessonite"] },
    { theme: "Metals And Alloys", words: ["chromium","palladium","beryllium","vanadium","cadmium","gunmetal","iridium","rhodium","niobium","tungsten","tantalum","zirconium","scandium","actinium"] },
    { theme: "Kitchen Gadgets", words: ["microwave","saucepan","casserole","spatula","colander","ramekin","skillet","griddle","cauldron","teakettle","processor","crockpot","stockpot","mandoline"] },
    { theme: "Herbs And Spices", words: ["cardamom","turmeric","rosemary","tarragon","marjoram","cinnamon","coriander","fenugreek","arrowroot","chervil","allspice","spearmint"] },
    { theme: "Sports", words: ["baseball","football","softball","handball","badminton","athletics","taekwondo","triathlon","lacrosse","billiards","wrestling","paintball","dodgeball","snowboard","bodyboard"] },
    { theme: "Olympic Sports", words: ["swimming","curling","shooting","canoeing","climbing","cycling","marathon","decathlon","fencing","sailing","wrestling","triathlon","taekwondo","badminton","biathlon","kayaking"] },
    { theme: "Poker Terms", words: ["showdown","straight","bluffing","checking","raising","folding","betting","jackpot","wildcard","cardshark","trapping","bankroll","overbet"] },
    { theme: "Weather And Seasons", words: ["monsoon","harvest","blossom","solstice","equinox","frostbite","sunburn","humidity","overcast","rainfall","downpour","snowfall","sunshine","daylight","nightfall","twilight"] },
    { theme: "More Countries", words: ["colombia","honduras","paraguay","uruguay","ecuador","zimbabwe","tanzania","botswana","mauritius","cameroon","malaysia","pakistan","slovakia","portugal"] },
    { theme: "More Musical Instruments", words: ["accordion","mandolin","dulcimer","bagpipes","ocarina","melodica","theremin","marimba","celesta","autoharp","harmonica"] },
    { theme: "Body Systems", words: ["skeletal","muscular","digestive","nervous","endocrine","lymphatic","vascular","cardiac","cellular","arterial","urinary","excretory"] },
    { theme: "Famous Explorers", words: ["magellan","columbus","cousteau","pizarro","vespucci","mackenzie","cartier","champlain","coronado","stanley","amundsen","raleigh","frobisher"] },
    { theme: "Art Movements", words: ["baroque","realism","futurism","modernism","mannerism","symbolism","fauvism","dadaism","collage","orphism","abstract","vorticism"] },
    { theme: "Literary Genres", words: ["mystery","fantasy","thriller","romance","tragedy","folklore","dystopia","biography","allegory","narrative","western","adventure","suspense"] },
    { theme: "Vegetables", words: ["broccoli","zucchini","eggplant","cucumber","artichoke","asparagus","butternut","rutabaga","radicchio","kohlrabi","parsnip","scallion","shallot","cabbage","spinach","celeriac","chicory"] },
    { theme: "Fruits", words: ["pineapple","blueberry","raspberry","cranberry","nectarine","persimmon","mandarin","starfruit","jackfruit","kumquat","honeydew","tangerine","plantain","avocado","apricot"] },
    { theme: "Sauces And Condiments", words: ["ketchup","mustard","sriracha","teriyaki","barbecue","marinara","guacamole","chutney","vinegar","tabasco","bechamel","remoulade"] },
    { theme: "Desserts", words: ["macaroon","meringue","tiramisu","baklava","shortcake","truffle","sherbet","popsicle","marzipan","streusel","panettone","cannoli","biscotti"] },
    { theme: "Beverages", words: ["lemonade","chocolate","smoothie","milkshake","espresso","americano","macchiato","affogato","cocktail","mocktail","kombucha","horchata","daiquiri","margarita","bellini"] },
    { theme: "Board Game Play Terms", words: ["gameboard","scorecard","opponent","strategy","teammate","referee","timeout","penalty","victory","champion","gameplay","tabletop","rulebook","tiebreak","overtime","stalemate","checkmate"] },
    { theme: "More Occupations", words: ["historian","physician","columnist","biologist","geologist","zoologist","economist","therapist","architect","violinist","dietician","librarian","secretary","carpenter","mechanic"] },
    { theme: "Natural Disasters", words: ["landslide","wildfire","flooding","drought","sinkhole","cyclone","tsunami","blizzard","eruption","twister","avalanche","hurricane","lightning","outbreak","mudslide","whirlpool"] },
    { theme: "Space Exploration", words: ["spaceship","spacesuit","moonwalk","touchdown","orbiting","reentry","liftoff","docking","gravity","capsule","payload","countdown","blastoff"] },
  ],
};
